#!/usr/bin/env bash
# Read the /etc/passwd file line by line using a while loop and IFS
while IFS=: read -r username _ uid gid info home shell; do
    # Extract additional information from the gecos field
    IFS=',' read -r _ _ _ info <<< "$info"

    # Display the desired information
    echo "The user $username is part of the $gid gang,lives in $home and rides $shell. USER ID's place is protected by the passcode $info, more info about the user here: $info"
done < /etc/passwd
