#!/usr/bin/env bash
# Initialize a counter
counter=0
# Using a while loop to display "Best School" 10 times
while [ $counter -lt 10 ]; do
     if [ $counter -eq 8 ]; then
        # Display "Best School" and then "Hi" on a new line for the 9th iteration
        echo -e "Best School\n"
        echo " Hi"
    else
        # Display "Best School" for other iterations
        echo "Best School"
    fi
    ((counter++))
done
