#!/usr/bin/env bash
# Initialize variables
hour=0
minute=1

# Using a while loop to display the time
while [ $hour -le 12 ]; do
printf "Hour: %02d\n" $hour    
while [ $minute -le 59 ]; do
        # Display the current time
        printf "%02d\n" $minute

        # Increment the minute
        ((minute++))
    done

    # Reset minute for the next hour
    minute=1

    # Increment the hour
    ((hour++))
done
